

spring:

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  application:
    name: SchoolRanking



  datasource:
    url: jdbc:postgresql://db:5432/schoolranking_dev
    username: postgres
    password: your_secure_password_here
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null  # Exclude all null fields globally
    
  jpa: 
    hibernate:
      ddl-auto: create-drop 
      # format_sql: true
     
    # show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect        #This tells Hibernate (the ORM used by Spring Data JPA) how to generate SQL statements that are optimized for PostgreSQL.

server:
  servlet:
    context-path: /api # This automatically prefixes every controller path with /api



# logging:
#   level:
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
