

spring:

  profiles:
    active: dev

  application:
    name: SchoolRanking



  datasource:
    url: jdbc:postgresql://localhost:5444/SchoolRanking
    username: tigana
    password: password
    driver-class-name: org.postgresql.Driver

  jpa: 
    hibernate:
      ddl-auto: create-drop
      format_sql: true
     
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        #This tells Hibernate (the ORM used by Spring Data JPA) how to generate SQL statements that are optimized for PostgreSQL.

server:
  servlet:
    context-path: /api # This automatically prefixes every controller path with /api



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
